######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 22 21:05:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src/cue src/ui
INCLUDEPATH += . src/ui src/cue

# Input
HEADERS += src/cue/cue.hpp \
           src/ui/MainWindow.hpp
SOURCES += src/main.cpp src/ui/MainWindow.cpp
